apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-sync
  namespace: startmeup
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: example-sync
  data:
    - secretKey: foobar
      remoteRef:
        key: secret/foo
        property: my-value