apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://eit-cluster-public-vault-9bdacbf0.95d8aa20.z1.hashicorp.cloud:8200"
      path: "secret"
      namespace: "admin"
      version: "v2"
      auth:
        tokenSecretRef:
          namespace: external-secrets
          name: "vault-token"
          key: "token"